apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
  namespace: mono
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    spec:
      containers:
        - name: monolith
          env:
            - name: LOGIN_MAX_CONCURRENCY
              value: "8"
          resources:
            requests:
              cpu: 3900m
              memory: 7680Mi
            limits:
              cpu: 7800m
              memory: 15360Mi
