apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-service
  namespace: msa
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: item-service
          resources:
            requests:
              cpu: 750m
              memory: 1296Mi
            limits:
              cpu: 2300m
              memory: 3456Mi
