apiVersion: v1
kind: ResourceQuota
metadata:
  name: msa-resource-quota
  namespace: msa
spec:
  hard:
    requests.cpu: "15800m"
    requests.memory: "27648Mi"
    limits.cpu: "15800m"
    limits.memory: "27648Mi"
