apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: msa
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: transaction-service
          resources:
            requests:
              cpu: 1000m
              memory: 3024Mi
            limits:
              cpu: 4000m
              memory: 10368Mi
