apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: msa
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: transaction-service
          resources:
            requests:
              cpu: 2000m
              memory: 3456Mi
            limits:
              cpu: 6800m
              memory: 12096Mi
