apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: msa
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api-gateway
          resources:
            requests:
              cpu: 980m
              memory: 1920Mi
            limits:
              cpu: 1950m
              memory: 3840Mi
