apiVersion: batch/v1
kind: Job
metadata:
  name: item-migration-job
  namespace: msa
spec:
  backoffLimit: 3
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      restartPolicy: OnFailure
      containers:
        - name: migration
          image: skripsi/item-service:local
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          envFrom:
            - secretRef:
                name: item-service-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          command:
            - /bin/sh
            - -ec
            - goose -dir /app/migrations postgres "$DATABASE_URL" up
