targetSystem: linux

datadog:
  apiKeyExistingSecret: datadog-secret
  clusterName: skripsi-msa

  tags:
    - env:benchmark
    - project:skripsi-benchmark
    - architecture:microservices

  logs:
    enabled: true
    containerCollectAll: true

  apm:
    portEnabled: true
    socketEnabled: false

  dogstatsd:
    port: 8125
    useHostPort: true
    nonLocalTraffic: true

  processAgent:
    enabled: true
    processCollection: true

  kubeStateMetricsCore:
    enabled: true

clusterAgent:
  enabled: true
  admissionController:
    enabled: true
    mutateUnlabelled: false
