apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
  namespace: mono
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    spec:
      containers:
        - name: monolith
          resources:
            requests:
              cpu: 7900m
              memory: 13824Mi
            limits:
              cpu: 15800m
              memory: 27648Mi
