apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: msa
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: auth-service
          env:
            - name: LOGIN_MAX_CONCURRENCY
              value: "1"
          resources:
            requests:
              cpu: 500m
              memory: 960Mi
            limits:
              cpu: 975m
              memory: 1920Mi
