apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: msa
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api-gateway
          resources:
            requests:
              cpu: 500m
              memory: 960Mi
            limits:
              cpu: 975m
              memory: 1920Mi
