apiVersion: v1
kind: ResourceQuota
metadata:
  name: mono-resource-quota
  namespace: mono
spec:
  hard:
    requests.cpu: "15800m"
    requests.memory: "27648Mi"
    limits.cpu: "15800m"
    limits.memory: "27648Mi"
