apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
  namespace: mono
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: monolith
          resources:
            requests:
              cpu: 1975m
              memory: 3456Mi
            limits:
              cpu: 3950m
              memory: 6912Mi
