apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - resourcequota.yaml
  - hpa.yaml
patches:
  - path: deployment-patch.yaml
images:
  - name: REPLACE_WITH_MONOLITH_ECR_IMAGE
    newName: replace-me.dkr.ecr.ap-southeast-1.amazonaws.com/skripsi/monolith
    newTag: latest
