name: skripsi-monolith

services:
  monolith:
    build:
      context: ../..
      dockerfile: monolith/Dockerfile
    image: skripsi/monolith:local
    container_name: skripsi-monolith
    restart: unless-stopped
    env_file:
      - ../../env/monolith.env
    ports:
      - "8080:8080"
    networks:
      - skripsi-local

networks:
  skripsi-local:
    external: true
